name       : akonadi-import-wizard
version    : 18.12.1
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/akonadi-import-wizard-18.12.1.tar.xz : b2dc7882d394610ce42a17290d41f0ef4dae4de4bdd82e6f0c11d1b0afb62527
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Assistant to import PIM data from other applications into Akonadi
description: |
    Assistant to import PIM data from other applications into Akonadi for use in KDE PIM applications.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kauth-devel
    - kconfig-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmail
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libassuan-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailcommon-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
