name       : akonadi-import-wizard
version    : 20.12.1
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/akonadi-import-wizard-20.12.1.tar.xz : ff9fff17f16cbdcc1fd76cc3612dab0d2642068bc7af9d3b839eae2ff67eb0f1
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Assistant to import PIM data from other applications into Akonadi
description: |
    Assistant to import PIM data from other applications into Akonadi for use in KDE PIM applications.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
