name       : akonadi-import-wizard
version    : 21.08.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/akonadi-import-wizard-21.08.3.tar.xz : aaaaedc234e73955ed7780eba5d1df8b30ff2a0dad110900ac64baf89cc0f4ea
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Assistant to import PIM data from other applications into Akonadi
description: |
    Assistant to import PIM data from other applications into Akonadi for use in KDE PIM applications.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
