name       : akonadi-import-wizard
version    : 21.04.1
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/akonadi-import-wizard-21.04.1.tar.xz : 8877940861e54a6b7dce2ebc95f9d15417f37df3f0c4514545d433a96f7ff509
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Assistant to import PIM data from other applications into Akonadi
description: |
    Assistant to import PIM data from other applications into Akonadi for use in KDE PIM applications.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-contacts-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - mailcommon-devel
    - mailimporter-devel
    - pimcommon-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
