name       : akonadi-import-wizard
version    : 20.08.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/akonadi-import-wizard-20.08.2.tar.xz : 639d72ae3d32f681ddb046a87d625871b485785602cf35b817e89004def4dc5e
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Assistant to import PIM data from other applications into Akonadi
description: |
    Assistant to import PIM data from other applications into Akonadi for use in KDE PIM applications.
builddeps  :
    - pkgconfig(libical)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - gpgme-qt-devel
    - karchive-devel
    - kcontacts-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidentitymanagement-devel
    - kimap-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
    - libkleo-devel
    - mailcommon-devel
    - mailimporter-devel
    - messagelib-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
